### ISSUE TITLE
PATH not set correctly

### ISSUE THREAD

**Issue by linusboyle** [antony-jr/insight#2]
Hello,

Thanks for your work! I'm currently using insight as primary gdb frontend. The problem is that insight cannot use my system `ps` and say, `xdg-open` .etc. Chances are that the $PATH shell variable is not correctly set.

Looking into the source, I found `insight/AppDir/usr/bin/insight-wrapper` with this:

```bash
export PATH=$(pwd)/bin
```

Should we change it to

```bash
export PATH=$PATH:$(pwd)/bin
```

**Comment by antony-jr** [comment]
@linusboyle Does it work on your computer now ?
**EDIT**: Thank you , that did the job. I will update the upstream repository and then do the changes.

**Comment by linusboyle** [comment]
> @linusboyle Does it work on your computer now ?
> **EDIT**: Thank you , that did the job. I will update the upstream repository and then do the changes.

@antony-jr Yeah, applying the change works fine now for me.
